import ROOT
import math 
import time
#from plot_dict import *
#This script is used to plot a atacked cutflow using the root file generated by xsWeightCutflow.py script

dataset = ["QCD_1000to1400",
                   "QCD_120to170",
                   "QCD_1400to1800",
                   "QCD_15to30",
                   "QCD_170to300",
                   "QCD_1800to2400",
                   "QCD_2400to3200",
                   "QCD_300to470",
                   "QCD_30to50",
                   "QCD_3200toInf",
                   "QCD_470to600",
                   "QCD_800to1000",
                   "QCD_80to120",
                   "QCD_50to80",
                   "QCD_600to800",
                   "ST_s-channel_4f",
                   "TTTo2L2Nu",
                   "TTToHadronic",
                   "TTToSemiLeptonic",
                   "W",
                   "WW",
                   "WZ",
                   "ZZ",
                   "DYlow",
                   "DY",
                   "Data"]

file_bbtt = ROOT.TFile("xsWeightCutHist.root")


#A lot of it is specific to the case I was working with and hence it need to be modified a bit when the time comes

workdir =file_bbtt.GetDirectory("September1check")
QCD_Histo = workdir.Get(dataset[0]).Clone()
QCD_Histo.Reset()
DY_Histo= workdir.Get(dataset[0]).Clone()
DY_Histo.Reset()
ST_Histo = workdir.Get(dataset[0]).Clone()
ST_Histo.Reset()
WJets_Histo = workdir.Get(dataset[0]).Clone()
WJets_Histo.Reset()
TT_Histo = workdir.Get(dataset[0]).Clone()
TT_Histo.Reset()
DiBoson_Histo = workdir.Get(dataset[0]).Clone()
DiBoson_Histo.Reset()
Data = workdir.Get(dataset[25])

QCD_Histo.Add(workdir.Get(dataset[0]))
QCD_Histo.Add(workdir.Get(dataset[1]))
QCD_Histo.Add(workdir.Get(dataset[2]))
QCD_Histo.Add(workdir.Get(dataset[3]))
QCD_Histo.Add(workdir.Get(dataset[4]))
QCD_Histo.Add(workdir.Get(dataset[5]))
QCD_Histo.Add(workdir.Get(dataset[6]))
QCD_Histo.Add(workdir.Get(dataset[7]))
QCD_Histo.Add(workdir.Get(dataset[8]))
QCD_Histo.Add(workdir.Get(dataset[9]))
QCD_Histo.Add(workdir.Get(dataset[10]))
QCD_Histo.Add(workdir.Get(dataset[11]))
QCD_Histo.Add(workdir.Get(dataset[12]))
QCD_Histo.Add(workdir.Get(dataset[13]))
QCD_Histo.Add(workdir.Get(dataset[14]))

ST_Histo.Add(workdir.Get(dataset[15]))

TT_Histo.Add(workdir.Get(dataset[16]))
TT_Histo.Add(workdir.Get(dataset[17]))
TT_Histo.Add(workdir.Get(dataset[18]))

WJets_Histo.Add(workdir.Get(dataset[19]))

DiBoson_Histo.Add(workdir.Get(dataset[20]))
DiBoson_Histo.Add(workdir.Get(dataset[21]))
DiBoson_Histo.Add(workdir.Get(dataset[22]))

DY_Histo.Add(workdir.Get(dataset[23]))
DY_Histo.Add(workdir.Get(dataset[24]))

color_DiBoson="#ffcc66"
color_TT="#4496c8"
color_WJets="#9999cc"
color_QCD="#12cadd"
color_ST="#990099"
color_DY="#cc6666"

DiBoson_Histo.SetFillColor(2)
TT_Histo.SetFillColor(3)
WJets_Histo.SetFillColor(4)
QCD_Histo.SetFillColor(5)
ST_Histo.SetFillColor(6)
DY_Histo.SetFillColor(7)



backgroundStack = ROOT.THStack('backgroundStack','backgroundstack')
backgroundStack.Add(DY_Histo,'HIST')
backgroundStack.Add(ST_Histo,'HIST')
backgroundStack.Add(QCD_Histo,'HIST')
backgroundStack.Add(WJets_Histo,'HIST')
backgroundStack.Add(TT_Histo,'HIST')
backgroundStack.Add(DiBoson_Histo,'HIST')


Data.SetMarkerStyle(20)
Data.SetMarkerSize(1.5)
#Data.HistogramName.Sumw2()	


theCanvas = ROOT.TCanvas("theCanvas","theCanvas")

backgroundStack.SetMaximum(max(backgroundStack.GetMaximum(),Data.GetMaximum()))

backgroundStack.Draw()
Data.Draw('SAME e1')
backgroundStack.GetYaxis().SetTitle("Events")
backgroundStack.GetXaxis().SetTitle("Weights_and_Selections")
backgroundStack.GetYaxis().SetTitleOffset(1.58)
backgroundStack.GetXaxis().SetLabelSize(0.0)

theLegend = ROOT.TLegend(0.61,0.61,0.88,0.88)
theLegend.AddEntry(Data,'Observed','pe')
theLegend.AddEntry(DiBoson_Histo,'DiBoson','f')
theLegend.AddEntry(TT_Histo,'TTbar','f')
theLegend.AddEntry(WJets_Histo,'WJets','f')
theLegend.AddEntry(QCD_Histo,'QCD','f')
theLegend.AddEntry(ST_Histo,'ST_s_Channel','f')
theLegend.AddEntry(DY_Histo,'Drell-Yan','f')
theLegend.Draw('SAME')

#also draw the preliminary warnings
cmsLatex = ROOT.TLatex()
cmsLatex.SetTextSize(0.06)
cmsLatex.SetNDC(True)
cmsLatex.SetTextFont(61)
cmsLatex.SetTextAlign(11)
cmsLatex.DrawLatex(0.1,0.92,"CMS")
cmsLatex.SetTextFont(52)
cmsLatex.DrawLatex(0.1+0.08,0.92,"Preliminary")

time.sleep(100)
